### ISSUE TITLE
Feedback on v3

### ISSUE THREAD

**Issue by DamienCassou** [browserpass/browserpass-extension#115]
Here is some feedback on browserpass v3:

- I'm very happy that you guys keep on maintaining browserpass. It's a very useful extension. Thank you so much.

- I really like the idea of the domain badge to filter the entries. It both brings security and is very easy to get rid of.

- I also like that the entries are sorted based on usage and that I can just press <kbd>RET</kbd> to activate the first one.

- I don't see the benefit of having the number of matching entries always visible as a badge on the extension's icon. It just doesn't bring me any value and it clutters the tool bar. (#103)

- On Firefox, most icons are just black with transparent background. This makes the browserpass icon stand out quite a bit for, in my opinion, no particular reason.

- The popup is the only one of all my extensions to be dark. It's not really a problem, but I like consistency :-). (#98)

- The currently selected entry has a background color which is not different enough from the normal background for me to quickly see what entry is active. My vision is not really good so it might just be me.

- The icon to go to the url attached to an entry is gone. I didn't use it often, but it was sometimes very useful.

I also lack support for OTP but that is taken care of separately (#76).

**Comment by DamienCassou** [comment]
None of the problems mentioned above is more important than #104 though!

**Comment by maximbaz** [comment]
Thanks for the feedback! It does sound that we made the right call to accept #103 and #98, since you also want both of them.

To give you some extra details: 

- The logo was discussed a lot and has been very carefully chosen, and we are all very fond of it, so it is not going to change 😉 
- The "Go to URL" button was intentionally removed because people seemed to confuse Browserpass for a bookmark manager (which it totally isn't), the only reason this functionality exists is to assist with modal HTTP auth, and given than the majority of websites don't use modal HTTP auth, having the button always visible in front of every password entry wasn't very useful. But we still have the keyboard shortcuts for this functionality (Ctrl+G and Ctrl+Shift+G) 🙂

**Comment by DamienCassou** [comment]
Thank you for your answers. Please close this issue whenever you want.
