### ISSUE TITLE
Show store and path only if there is a reason to do so

### ISSUE THREAD

**Issue by mithodin** [browserpass/browserpass-extension#116]
Having the passwords window show the store and path might be useful if there is more than one store and more than one folder in that store, but if there is neither, it's just superfluous information that's repeated multiple times.
So the store name should only be displayed if there is more than one store. The path should only be displayed if there are actual subfolders inside the store.
It's a small thing, but it would make the ui a little better, imho.

**Comment by maximbaz** [comment]
Thanks for the feedback 🙂 

The choice of always showing path and store was intentional, to have a single design that looks good and identical for all users, regardless of their setup. To make it look better, we went for a 2-line design in order to better highlight what is the important distinguishing information to look at. The first line has optional information which you might or might not be interested (and therefore a bit smaller in size), while the second line is what you usually look at, and is bigger in size.

However, thinking about it now, we can consider hiding the password store badge entirely if you configure password store with an empty name in the options - what we show currently in such case is weird anyway. Do you agree, @erayd?

We will keep the 2-line design (because for example recency icon is displayed on the first line too), and I think we will keep showing path always, to always have at least something on the fist line, to make it simple to maintain a nice design and to keep UI consistent in case your popup contains a mix of passwords from both root and subfolders - when a password is stored is root, it's a tiny almost invisible `/` anyway.

**Comment by erayd** [comment]
@maximbaz I think we should keep the badge, even if there's only one store. We agonised over this for ages, and if I remember rightly, we wanted the badge to stay because it provided a useful visual distinction between the lines - without it, it became somewhat ambiguous which line was the entry, and which line was the path, recency etc.

That said, if there is only one store, perhaps we could put something else in the badge area for that case, provided it's still visually distinctive.

**Comment by maximbaz** [comment]
Ah, this is entirely true, I remember now, without the badge the distinction between the two lines looked not clear and quite weird.

I agree, we should keep everything as it is then, @mithodin please try to play with configuring password store name and colors if the badge really bothers you 🙂

**Comment by mithodin** [comment]
I see you've put a lot of thought into this. It's fine.
