### ISSUE TITLE
Username is overwritten with site name on autofill

### ISSUE THREAD

**Issue by rgammans** [browserpass/browserpass-extension#117]
### General information

-   Linux Debian Stretch
-   Chrome 73
-   Information about the host app:
    -   If built from sources, put a commit id (`$ git describe --always`): 6422e660f1731fd779fe75c76aac0f23151e3ac4
-   Information about the browser extension:
    -   How did you install it?
     Installed via chrome store/updated automaticaly from 2.x
---

### Exact steps to reproduce the problem
0. Ensure default password is in extenstion config is blank
1.  On the console
pass edit foo.com
Add a single line with a password.

2. Visit foo.com

3. Select foo.lcom password optoin

### What should happen?
The username shal be left alone and the password field filled in. (with

### What happened instead?
The username field is filled withthe site url (foo.com)

**Comment by maximbaz** [comment]
Hey, it is interesting because Browserpass has never supported skipping a username. Might I ask why do you want this behavior, what is the real-world scenario when you want to only auto-fill password, but not the username, when both are being asked?

**Comment by erayd** [comment]
@rgammans A possible workaround could be to click the browserpass icon, *then* fill the username. That way you would be overwriting whatever browserpass filled into that field, rather than the other way around.

The reason it's trying to fill the site (e.g. foo.com) into the username field is because you haven't specified a username in the password file (or set a default one). We assume that the filename is the username when this field is left unset.

**Comment by maximbaz** [comment]
@erayd's suggestion of filling username could be handy, also in case you have a username that is more common than other usernames, you can put _that one_ in Browserpass options - then after filling the form with browserpass, in some cases all you need to do is to press Enter, and in other cases you will additionally change the username.

You can then additionally put `user: XXX` only in those password entries whose username differs from your default one (do this, automation is the key in the modern world! 😜)

I'm going to close this ticket since it doesn't sounds like something we will try to implement 🙂

**Comment by rgammans** [comment]
You would think that would  work; but it doens't because many sites have JS wihich clears the password if the username changes. ( Oh ; and I have auto submit turned-on)
