### ISSUE TITLE
Erayd is not in authors in about:addons

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#121]
https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/
https://addons.mozilla.org/en-US/firefox/addon/browserpass-otp/
show: "by Maxim Baz, Erayd"

While only Maxim Baz is shown on about:addons

**Comment by erayd** [comment]
@maximbaz Low priority - this really doesn't bother me at all. Feel free to close this if you can't find where this is set; it's not obvious, and I think you already set me as an author everywhere it's possible to do so. Maybe it's just cached somewhere?

**Comment by maximbaz** [comment]
I just checked, it seems everything is set. I bet it's either cached (just like we saw with logo, remember), or somehow related to the fact that "author" field in the manifest [cannot contain multiple authors](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/author).

> The extension's author, intended for display in the browser's user interface. If the developer key is supplied and it contains the "name" property, it will override the author key. There's no way to specify multiple authors.

What's more important is that @erayd has full access to release extensions, in case something happens to me. Closing since it doesn't seem like something we can fix on our side 🙂
