### ISSUE TITLE
Security guarantees regarding file access

### ISSUE THREAD

**Issue by FabianHenneke** [browserpass/browserpass-extension#142]
The README claims the following security guarantee:

> Given full control of the non-native component of the extension, an attacker may be able to extract passwords stored in the configured repository, but cannot obtain files elsewhere on the filesystem or execute arbitrary code outside of the browser.

I agree that browserpass-extension can (very likely) not be abused to make browserpass-native execute arbitrary code. But I would think that by simply sending a directory of the attacker's choice as a store while fetching a .gpg file in it, unrelated encrypted files could be leaked in plaintext back to browserpass-extension. Is that correct or am I missing a safeguard here?

**Comment by maximbaz** [comment]
This is true, because the password store is configurable in the browser extension, theoretically an attacker will be able to list (and decrypt unless decryption requires e.g. touching a Yubikey) `.gpg` files anywhere on the file system. It's not something we can guard against I'm afraid, so we can only update our security principles in the README to clarify this point.
