### ISSUE TITLE
Single words matching domain extensions

### ISSUE THREAD

**Issue by r7l** [browserpass/browserpass-extension#170]
### General information

-   Operating system + version: **Gentoo 17.1**
-   Browser + version: **Chromium 77.0.3865.75**
-   Information about the host app:
    -   How did you install it? **Installed via a package manager**
    -   If installed an official release, put a version **3.0.6**
-   Information about the browser extension:
    -   How did you install it? **Installed via Chrome webstore**
    -   Browserpass extension version as reported by your browser: **3.1.1**

---

### Exact steps to reproduce the problem

1. Add directory to pass store containing a single word that might be a domain extension (lets say "**com**")

2. open a URL in browser with this domain extension: **domain.com**

3. get all the passwords existing inside this directory, including all sub directories

### What should happen?

I am not sure if this is by design but it's actually weird to have all the passwords for a word coming up if a domain extension equals that word used as directory name. Giving the number of "funky" domain extensions we have now, it can cause quite some confusion. The other thing is that if you have custom domain extensions like "local" or anything and directories like this.

Wouldn't it be better to have domain names starting to work if there is at least a **.** inside the string? So any **domain.com** works but not **com** itself.

### What happened instead?

Every password inside that directory pops up. This is confusing if you have a directory that has the same name as some existing domain extension.

**Comment by maximbaz** [comment]
Hey!

You are right that it is by design, Browserpass is expecting a certain structure in [organization of your password store](https://github.com/browserpass/browserpass-extension#organizing-password-store) in order to properly prepare a list of matching entries. There are valid cases where a dot is not expected to be part of the name, for example:

- For websites like `http://localhost:1234` or `https://router/` you would create `localhost.gpg` and `router.gpg` respectively
- For local development, one might want to create a folder `local` with a few test credentials, and then expect to see all these credentials on all local domains like `http://app1.local` or `http://app2.local`

Also note that domain lookup is done from right to left, so while `com/example.gpg` will indeed popup on `https://github.com`, `com/example.com.gpg` will not, the latter will only appear on `https://example.com` even though it is residing in a `com` folder.

It sounds to me that in your workflow you have some pass entries that you want Browserpass to recognize (such as `github.com.gpg`) and other pass entries that you want Browserpass to ignore (such as `com/bla.gpg`). It is a valid scenario! And in fact we have already implemented [a solution for this](https://github.com/browserpass/browserpass-extension/pull/161), but it's not available in the latest release just yet. The approach would be to define an `ignore` section in your `browserpass.json` file in the root of your password store, which would allow you to create any number of ignore rules (for example, you could make Browserpass ignore the entire `com` folder).

Does this sound like a reasonable solution? I will go ahead an release a new version right now, so you can give it a try.

**Comment by r7l** [comment]
Ya this is exactly what i was looking for. I haven't seen this issue yet but maybe i was just looking for the wrong keywords. Thanks allot!

**Comment by maximbaz** [comment]
3.2.0 has been released, enjoy!

**Comment by erayd** [comment]
I actually consider this a bug. `com` is a TLD, but is not a valid domain, and as such should never match unless the user is actually visiting a site called 'com'.

@maximbaz Do you have any objection to me fixing this?

**Comment by maximbaz** [comment]
Will it break my example with `local` folder?

**Comment by erayd** [comment]
It would break the `local` example, because 'local' is not a valid domain. However, isn't this partly why we have the history feature? After you've used it once, it'll show up regardless, even if there is no domain match.

`localhost` would still work just fine, because it's a full match.

**Comment by maximbaz** [comment]
Ah right I forgot about the full match, in this case sounds like a good optimization to me!

**Comment by r7l** [comment]
If you go through that, there are a large (and growing) number of actual TLDs that might match for one reason or the other. Stuff like **.chat** might easily match any **chat** directory users might have and that's what i had in mind initially because i don't really see a need for it. But the `browserpass.json` should do the job for me.

**Comment by maximbaz** [comment]
We are using a library which (should) know all existing TLDs, so at least we will not hardcode any TLDs ourselves...
