### ISSUE TITLE
Regression: badly rendered icon in Firefox

### ISSUE THREAD

**Issue by maximbaz** [browserpass/browserpass-extension#190]
Guess we haven't tested in Firefox after merging light theme PR 😄 

Notice the button that removes domain filter:

![image](https://user-images.githubusercontent.com/1177900/67906743-e0a27780-fb75-11e9-886c-37070c3034b8.png)

@532910, you use Firefox, do you also reproduce?

It's supposed to be red and look like this:

![image](https://user-images.githubusercontent.com/1177900/67906702-cb2d4d80-fb75-11e9-93e7-c3248e8fab93.png)

**Comment by erayd** [comment]
Looks like it still shows up if you have never set a theme, but is absent in both light and dark themes if one has been set.

I'll fix it.

**Comment by maximbaz** [comment]
Oh, nice catch, that's why nobody noticed 😄

**Comment by 532910** [comment]
Just took it as a new design, both looks well enough (:

**Comment by erayd** [comment]
This is really strange. All the colouring for that is in the SVG image, and I can't find anywhere that's explicitly overriding it. The shape is correct, which means the SVG is being displayed... it's just missing all the colour for some reason...

**Comment by maximbaz** [comment]
What's even more weird is that if you open this SVG in a new tab in Firefox from disk (e.g. `file:///home/maximbaz/browserpass-extension/src/popup/icon-bs-delete.svg`), it will be colorful, but if you open it from extension (e.g. `moz-extension://d0a6dec8-4c88-4050-a4e7-312b366cecee/popup/icon-bs-delete.svg`) then it will be black...

**Comment by erayd** [comment]
I am wondering if this is a Firefox bug... it's proving extremely hard to track down a cause in anything we've done. We obviously still need to fix it, but... it's really strange.

**Comment by maximbaz** [comment]
@erayd maybe not a bug after all but a wrong CSP 😉  I bisected:

```
b7782fb80628493f962fae0eda7d013dcf5a6b17 is the first bad commit
commit b7782fb80628493f962fae0eda7d013dcf5a6b17
Author: Fabian Henneke <FabianHenneke@users.noreply.github.com>
Date:   Fri May 3 09:08:22 2019 +0200

    Set an explicit, stricter CSP (#144)
```

**Comment by erayd** [comment]
Interesting. Although if it was just the CSP, then we shouldn't even be seeing the image shape, because it would be blocked entirely... and yet we are. CSP deny should be complete deny, not partial render.

**Comment by erayd** [comment]
The root cause of this appears to be a bug in Firefox's URL parsing, which returns a string `"null"` instead of an actual `null` value for the `origin` property under some circumstances.

I'm getting sick of just how many Firefox bugs I keep running into, particularly when contrasted with Chrome, where the APIs generally behave according to the spec.

**Comment by jplitza** [comment]
The problem isn't that the CSP is blocking the image *itself*, the problem is that it's blocking the inline CSS *within* the image. You need to set `style-src: 'self' 'unsafe-inline'` or outsource the CSS from the SVG(s? Should apply to all of them) to a separate file (or separate files). The latter seems unrealistic.
