### ISSUE TITLE
Regression: error on New Tab in Firefox

### ISSUE THREAD

**Issue by maximbaz** [browserpass/browserpass-extension#191]
It is supposed to show a full list of passwords, and it definitely worked like this in the past, not sure when it broke:

![image](https://user-images.githubusercontent.com/1177900/67906911-67efeb00-fb76-11e9-90bf-3f22a04c25b0.png)

**Comment by erayd** [comment]
Probably our origin change. I'll fix this one too.

**Comment by erayd** [comment]
The root cause of this appears to be a bug in Firefox's URL parsing, which returns a string `"null"` instead of an actual `null` value for the `origin` property under some circumstances.

I'm getting sick of just how many Firefox bugs I keep running into, particularly when contrasted with Chrome, where the APIs generally behave according to the spec.
