### ISSUE TITLE
Add a way to donate or support this project.

### ISSUE THREAD

**Issue by subdavis** [browserpass/browserpass-extension#244]
I'd like to financially support this extension with a small contribution.  I don't want to sponsor you because I want to focus my support on the browserpass project.

Please add a section to the readme explaining how I can do that.

**Comment by maximbaz** [comment]
Hey! Thanks for your desire to support the project 🙂 

It's my understanding that organizations usually establish a dedicated bank account because there are many people involved and there is a need to cover expenses that are only related to the project specifically (hosting, subscriptions, etc.). Neither of these really apply to Browserpass, we are in fact just two people who are core maintainers, with an awesome community around the project, and we don't have any costs or fees involved to keep the project alive - the only expense we have is our own time that we dedicate to the project 😉 

At this stage at least, I don't think it makes sense for us to create a dedicated bank account that will be able to accept and collect contributions, simply because we don't have any project-related expenses where we could use those money for.

@erayd feel free to add something if you have a different perspective 🙂

**Comment by erayd** [comment]
I agree with @maximbaz. We could probably sort something out with PayPal as a one-off if you *really* want to send us money... but this project has no expenses, so we really don't need it.

**Comment by subdavis** [comment]
I mean, it's not really about needing it.  It's about getting paid for your time.  Open source isn't charity.

Anyway, appreciate your work!   Cheers.

**Comment by maximbaz** [comment]
Sure thing 🙂 

Personally I do like what Github did with sponsorship for people, it's exactly that, to support a particular person for the time they put in their open source work. But organization-level sponsorship is too complicated to setup, especially if there is no need to cover any specific project expenses.

I think we got everything clarified, thus closing 👍
