### ISSUE TITLE
How to configure extension for remote native host application

### ISSUE THREAD

**Issue by harleypig** [browserpass/browserpass-extension#255]
### General information

-   Archlinux
-   Chromium
-   Information about the host app:
    -   How did you install it?
        pacman -S browserpass-native
    -   Browserpass host app version: 3.0.7
-   Information about the browser extension:
    -   How did you install it?
        pacman -S browserpass-chromium
    -   Browserpass extension version as reported by your browser:
        not installed
---

### What should happen?

Find documentation on how to configure the extension for remote native host app.

### What happened instead?

Couldn't find it.

I can configure a reverse proxy for nginx, I can password protect the endpoint and I can craft a systemd service file to start browserpass, but I cannot figure out how to configure the extension files to talk to my server.

I'm probably missing something obvious ... perhaps this extension is just not meant to talk to a remote server? If so, that would also mean the extension won't know how to handle a password prompt from the remote.

I have two use cases for wanting this.

The first is for myself. While I can clone my pass repo to my work machine, I can't install the browserpass program--my company uses bit9 for auditing and won't allow non-approved programs. And they won't approve browserpass. I can, however, install an extension. /shrug/

The second use case is that I want to provide password storage to family members who are less than technically minded. While I can give them an executable I can't guarantee where they'll install it and they will give up in frustration if it doesn't work the first time they try it. I can give them instructions on how to download and install an extension from my server.

Am I barking up the wrong tree?

Edit: proper tense looks good

**Comment by erayd** [comment]
> Find documentation on how to configure the extension for remote native host app.

You do not need to configure the extension for this at all. Provided the host app is installed correctly, the extension site will work straight out of the box.

Configuration for the host app is documented [url=https://github.com/browserpass/browserpass-native#configure-browsers]here[/url]. This step is needed so that the browser knows where to find the host app and which extensions are permitted to communicate with it.

> I can craft a systemd service file to start browserpass...

The Browserpass host app is not a network service. You cannot run it this way.

> Am I barking up the wrong tree?

Unfortunately yes. Native host applications aren't network things; they are local programs which are executed by the web browser itself, in response to a request from the extension to talk to it. There's no network connectivity involved. This means that you cannot run the host remotely; it must be executed on the same machine as the browser.

**Comment by harleypig** [comment]
Thanks.

**Comment by erayd** [comment]
No worries. I wish you the best of luck with finding a password manager solution that meets your needs, as unfortunately it sounds like Browserpass isn't the best fit for what you're trying to achieve.

Have you considered using 1password for the friends & family case? That can be installed as an extension only, with no need for any other local programs to be installed. It's also a fair bit more usable for friends-and-family than pass is - pass is really intended for more technical users.

Regarding your own usage - it's much more cumbersome if you wish to continue using a pass-style method of password storage, but have you considered simply running pass on your remote machine via ssh, and copying the credentials across from there? Certainly a bit clunky, but better than nothing.

**Comment by maximbaz** [comment]
Just wanted to chip in with an additional idea

> The first is for myself. While I can clone my pass repo to my work machine, I can't install the browserpass program--my company uses bit9 for auditing and won't allow non-approved programs. And they won't approve browserpass. I can, however, install an extension. /shrug/

If executables are not allowed, what about scripts, shell scripts or python scripts for example? If you really want to continue using browserpass for your own usage, you could just implement native host part on your own - we have a backwards-compatible and documented protocol, and you don't even need to implement all features, only the subset that you actually use.

Native host is just a program that reads input on stdin and writes output to stdout, in a pre-defined format.

Here's an example of native host in bash: https://stackoverflow.com/a/24777120
Here's our protocol documentation: https://github.com/browserpass/browserpass-native/blob/master/PROTOCOL.md

You don't have to implement a very generic logic, for example hardcode stuff instead of respecting `settings` object coming from the browser extension, if that's easier. You are free to use any methods, you can call `pass` directly, you can use `gpg`, if all of these are also blocked, you can even call `ssh myhome pass "$@"` 😄 

Or!!! You can even make such script a thin wrapper over a real browserpass native host running on your home computer, i.e. your script should read stdin, send it fully over to your browserpass running on your home computer via ssh, read the output back and just pass the output further to its own stdout - it could be a one-line wrapper that takes care of remote communication with the real native host 😁 Just consider the security implications of sending your credentials over ssh.
