### ISSUE TITLE
Use fewer permissions

### ISSUE THREAD

**Issue by tomfitzhenry** [browserpass/browserpass-extension#265]
Per https://github.com/browserpass/browserpass-extension/blob/77f6d18f8ea92e68fc0c020cb4065283e45a78c2/src/manifest-firefox.json#L27-L39 , this extension requests a set of permissions on installation.

This extension is a privileged application, since it has access to a password store, so it'd be great if it relied on the web extension permission model to limit its privilege. A code audit could only go so far: it will miss some issues, and doesn't account for risks in the build and release process (see https://reproducible-builds.org/ ).

## Proposals to make permissions optional

Firefox considers the following permissions to be privileged enough to advise the user of:
clipboardWrite, webRequest, activeTab, `<all_urls>`, so let's focus on those.

### webRequest

Used for: injecting username/passwords into HTTP basic auth prompts.

Risk: **Medium**. This permission can be used to exfiltrate all your browsing metadata.

How to make it optional: set HTTP auth to be disabled by default. If a user chooses to enable it, request `webRequest` then.

### `tabs`/`<all_urls>`

Used for: Likely many things, but including: injecting a content script on all pages, to add a pass icon to username/passwords fields.

Risk: **High**. This permission can be used to exfiltrate all content (incl. input) of all pages you visit, or to inject arbitrary content into all pages you visit.

How to make it optional: don't add a content script to all pages. Instead, add an option (disabled by default) to control this. If/when the user enables this, request `<all_urls>`. this extension can use `activeTab` when this option is disabled, which allows this extension to inject a content script if/when the user chooses to interact with this extension, e.g. via the right click menu, or via the passff browser bar button.

### clipboardRead/clipboardWrite

Used for: copying username and passwords to the clipboard.

Risk: Low. A malicious extension could put malicious scripts in your clipboard, hoping that you paste them into a terminal?

How to make it optional: defer requesting `clipboardWrite` until the user chooses to copy to the clipboard.

*Disclaimer: I have opened a similar issue against passff: https://github.com/passff/passff/issues/472.*

**Comment by maximbaz** [comment]
Hello! 

Thanks for your effort and detailed explanation, definitely appreciated.

> This extension is a privileged application, since it has access to a password store, so it'd be great if it relied on the web extension permission model to limit its privilege. A code audit could only go so far: it will miss some issues, and doesn't account for risks in the build and release process (see https://reproducible-builds.org/ ).

I completely agree that web extension permission model should be used to not have more permissions than necessary to be able to provide the functionality, provided that it doesn't harm functionality or user experience.

> webRequest
> How to make it optional: set HTTP auth to be disabled by default. If a user chooses to enable it, request webRequest then.

I don't think this proposal follows web extension permission model, we shouldn't cripple extension functionality just for the sake of doing it. 

When you want to locate yourself in a maps application on Android, you get a prompt "May I use GPS? Always, This one time, No", and after you respond with a positive answer you get the functionality. It's unobtrusive, very easy to use.

Imagine if instead the application showed you a prompt "May I use GPS?", you tap "Yes" and then you got a different prompt "Ha, but go in application settings and enable this feature, because for security we disabled it". I feel like it will be faster to delete such application than going through the trouble of making it work 🙂 

> tabs/<all_urls>
> How to make it optional: don't add a content script to all pages. Instead, add an option (disabled by default) to control this. If/when the user enables this, request <all_urls>

Same as above, except this is a vital feature, in my mind it just doesn't make sense to provide browserpass that out of the box is unable to fill out login forms to some websites, and requires user to search in extension options how to fix the functionality.

> clipboardRead/clipboardWrite
> How to make it optional: defer requesting clipboardWrite until the user chooses to copy to the clipboard.

This I could be sold on, however (a) I even think we wanted to make it optional since the beginning, but users reported that it wasn't behaving well in Firefox, (b) the risk of this one is quite low, if this is the only permission that we conclude makes sense to make optional, honestly I wouldn't go through the trouble to implement it, to only have one optional permission, the clipboard... 🙂

**Comment by erayd** [comment]
Thanks @tomfitzhenry - I appreciate your analysis. I do agree with @maximbaz's overall assessment of the situation, but would like to make a few additional comments, particularly as we have discussed the optionality of all of these permissions before.

## WebRequest

This was actually implemented as an optional permission back in #6. However, we later discovered that requesting this permission later after install was often granted silently (possibly due to us already holding some other significant permissions). This means that having it be optional wasn't really gaining us anything in terms of security, because the browser would just auto-approve it and never notify or interact with the user at all - but it did introduce some inconsistency of behaviour, and a false sense of security. Firefox also occasionally refused to ask, and simply failed the request. As a result, we put it back on the main list of permissions requested at install-time, as the optional approach was actually worse.

## ActiveTab / <all_urls>

> How to make it optional: don't add a content script to all pages. Instead, add an option (disabled by default) to control this. If/when the user enables this, request <all_urls>. this extension can use activeTab when this option is disabled, which allows this extension to inject a content script if/when the user chooses to interact with this extension, e.g. via the right click menu, or via the passff browser bar button.

We *don't* add a content script to all pages. This is very deliberately the case, in order to reduce the possible attack surface. The only time we inject anything into a page is precisely as you suggest; i.e. when the user directly interacts with Browserpass (either via the icon popup, or via a keyboard shortcut) and tells it to do something that requires an injected script, such as filling in a login form.

> e.g. via the right click menu, or via the passff browser bar button.

We also don't use the right-click menu, and don't have anything to do with PassFF. Did you perhaps copy / paste this part of your issue report? You seem to be talking about a number of things we don't do.

We did actually have `<all_urls>` as an optional permission in the past, requested when needed. Unfortunately, `ActiveTab` doesn't allow access to non-root frames in the active tab (see [this Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=452944)), and some sites put their login forms in an iframe. To prompt on some sites and not on others makes for an inconsistent and very confusing user experience; even more so if we were to prompt for an origin domain they don't recognise (e.g. when an iframe login form is served from some third party). As such, `<all_urls>` was set as a mandatory permission in #22.

## clipboardRead / clipboardWrite

The biggest threat here is actually potential exfiltration of clipboard data, which you don't seem to have raised at all.

With that said, the possibility for abuse of `<all_urls>` *vastly* outweighs the possible harm that could be done by abusing the clipboard permissions. Given that attacking any of these permissions would require modifying the Browserpass source, and we can't reasonably make `<all_urls>` optional, I feel that putting core functionality like this behind a permissions popup (which also causes the Browserpass UI to close when it appears, because it loses focus) is just needlessly cumbersome and annoying to users, for very minimal gain. It's also worth noting that a source compromise removes most of the value of optional permissions anyway, because in the event that the user had not already granted the relevant permission, such an exploit could simply request it.

Overall, while I do appreciate you taking the time to file an issue report about this, I'm not really seeing anything here that is sensible for us to change. The reasons for requesting the permissions upfront rather than optionally afterwards are clear, and seem unlikely to change to any significant degree going forward.

**Comment by tomfitzhenry** [comment]
maximbaz@, thanks for your reply!

> Imagine if instead the application showed you a prompt "May I use GPS?", you tap "Yes" and then you got a different prompt "Ha, but go in application settings and enable this feature, because for security we disabled it". I feel like it will be faster to delete such application than going through the trouble of making it work slightly_smiling_face

The extension could prompt for the webBlocking permission (explaining why the permission was needed), and then enable HTTP basic auth interception in response. The user wouldn't need to be prompted, and then go to their options.

> > tabs/<all_urls>
> > How to make it optional: don't add a content script to all pages. Instead, add an option (disabled by default) to control this. If/when the user enables this, request <all_urls>
> 
> Same as above, except this is a vital feature, in my mind it just doesn't make sense to provide browserpass that out of the box is unable to fill out login forms to some websites, and requires user to search in extension options how to fix the functionality.

activeTab would work on all sites, so long as the user interacted with browserpass on that page.

> 
> > clipboardRead/clipboardWrite
> > How to make it optional: defer requesting clipboardWrite until the user chooses to copy to the clipboard.
> 
> This I could be sold on, however (a) I even think we wanted to make it optional since the beginning, but users reported that it wasn't behaving well in Firefox, (b) the risk of this one is quite low, if this is the only permission that we conclude makes sense to make optional, honestly I wouldn't go through the trouble to implement it, to only have one optional permission, the clipboard... slightly_smiling_face

Ah, it makes sense that it was made required in response to poor behaviour when it was optional.

**Comment by tomfitzhenry** [comment]
> This was actually implemented as an optional permission back in #6. However, we later discovered that requesting this permission later after install was often granted silently (possibly due to us already holding some other significant permissions). This means that having it be optional wasn't really gaining us anything in terms of security, because the browser would just auto-approve it and never notify or interact with the user at all - but it did introduce some inconsistency of behaviour, and a false sense of security. Firefox also occasionally refused to ask, and simply failed the request. As a result, we put it back on the main list of permissions requested at install-time, as the optional approach was actually worse.

Ah, I wasn't aware optional permissions had these sorts of issues.

> ## ActiveTab / <all_urls>
> 
> > How to make it optional: don't add a content script to all pages. Instead, add an option (disabled by default) to control this. If/when the user enables this, request <all_urls>. this extension can use activeTab when this option is disabled, which allows this extension to inject a content script if/when the user chooses to interact with this extension, e.g. via the right click menu, or via the passff browser bar button.
> 
> We _don't_ add a content script to all pages. This is very deliberately the case, in order to reduce the possible attack surface. The only time we inject anything into a page is precisely as you suggest; i.e. when the user directly interacts with Browserpass (either via the icon popup, or via a keyboard shortcut) and tells it to do something that requires an injected script, such as filling in a login form.


> 
> > e.g. via the right click menu, or via the passff browser bar button.
> 
> We also don't use the right-click menu, and don't have anything to do with PassFF. Did you perhaps copy / paste this part of your issue report? You seem to be talking about a number of things we don't do.

I did copy/paste this, but had tried to adapt it to browserpass (e.g. different clipboard permissions), and missed this! My bad.

The right-click menu comment was just meant to explain activeTab a bit more.

> We did actually have `<all_urls>` as an optional permission in the past, requested when needed. Unfortunately, `ActiveTab` doesn't allow access to non-root frames in the active tab (see [this Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=452944)), and some sites put their login forms in an iframe. To prompt on some sites and not on others makes for an inconsistent and very confusing user experience; even more so if we were to prompt for an origin domain they don't recognise (e.g. when an iframe login form is served from some third party). As such, `<all_urls>` was set as a mandatory permission in #22.

Ah yes, this makes sense why browserpass would want to want to inject into all frames, given sites use different frames for logins.

> It's also worth noting that a source compromise removes most of the value of optional permissions anyway, because in the event that the user had not already granted the relevant permission, such an exploit could simply request it.

Perhaps Firefox's rationale for developing optional permissions is that they are useful for users that won't just accept the permission?

> Overall, while I do appreciate you taking the time to file an issue report about this, I'm not really seeing anything here that is sensible for us to change. The reasons for requesting the permissions upfront rather than optionally afterwards are clear, and seem unlikely to change to any significant degree going forward.

Thanks for considering these!

**Comment by tomfitzhenry** [comment]
A further argument against worrying about permissions is that even if browserpass only used `activeTab` and `nativeMessaging` (its minimal set of permissions), a malicious browserpass could still exfiltrate all secrets, by enumerating them all and posting them to `malicious.example.com`.

**Comment by erayd** [comment]
> Perhaps Firefox's rationale for developing optional permissions is that they are useful for users that won't just accept the permission?

Asking for permissions at time-of-use can make it more obvious what those permissions are used for, so that the user can make a more informed decision than just allowing or denying the whole lot upfront. We've seen a significant shift in that direction on Android, for example.

That model isn't a good fit for Browserpass unfortunately - so given that we need them upfront, we do our best to ensure the permissions we do need are all documentated in the README - but I can certainly see a number of scenarios in which the ask-when-used approach would be superior.
