### ISSUE TITLE
Error after selecting password

### ISSUE THREAD

**Issue by skrat** [browserpass/browserpass-extension#268]
```
Error: Unable to fetch and parse login fields: Error: {"status":"error","code":24,"version":3000007,"params":{"action":"fetch","error":"Error: exit status 2, Stderr: gpg: decryption failed: No secret key\n","file":"xxx","message":"Unable to decrypt the password file","storeId":"default","storeName":"pass","storePath":"/home/skrat/.password-store"}}
```

browserpass-3.0.7-2
extension-3.7.2
arch linux / chromium

So the extension correctly shows available passwords but when selecting one, it errors out with the above. Any hints?

**Comment by erayd** [comment]
That is an issue with your GPG setup; not with Browserpass. Are you able to describe your setup in more detail?

**Comment by skrat** [comment]
@erayd I'm long time browserpass user and it this just broke recently with some updates I assume. Nothing unusual about my setup, `~/.password-store` as you can see in the error message. When using `pass` from terminal, it works as usual.

**Comment by skrat** [comment]
Actually, I'm using firejail. When I run `chromium` without it, browserpass works. I'm figuring out a proper firejail setup. I have whitelisted (read-only) `${HOME}/.password-store`.

**Comment by skrat** [comment]
Nevermind, I solved it with the following configuration (posting here for reference)

~/.config/firejail/chromium.local
```
whitelist ${HOME}/.password-store
read-only ${HOME}/.password-store

noblacklist ${HOME}/.gnupg
whitelist ${HOME}/.gnupg
```

**Comment by erayd** [comment]
> Actually, I'm using firejail.

This is probably the cause of your problems. Whitelisting `~/.password-store` isn't enough; you'll also need to allow it proper access to your GPG setup so that it can decrypt the contents of the password files. That is where it's having trouble; Browserpass is able to call a valid GPG binary, but that GPG binary cannot locate a suitable private key for decryption. Perhaps your firejail config is preventing GPG from accessing your keyring?

**Comment by cindrmon** [comment]
> I'm long time browserpass user and it this just broke recently with some updates I assume. Nothing unusual about my setup, ~/.password-store as you can see in the error message. When using pass from terminal, it works as usual.

I also have the same issue, yet I don't have firejail to begin with. I have able to recently setup browserpass for brave, and this error also appears whenever I try retrieving a password. I can't really pinpoint anymore what is the issure, because I have my `/.gnupg` folder all over the place, because of another program I'm using, which is antidot (that changes configuration files location to what presumes to be the proper folder structure for each). When running the antidot program, it clears the main `~/.gnupg` and moves them to `~/.local/share/gnupg`. Apparently, after setting gnupg-agent to recognise the new changes, only pass and gpg2 recognise the change. All other programs do not, and does not see any gpg keypairs from `~/.local/share/gnupg`, only on `~/.gnupg`. One of these is browserpass.

**Comment by skrat** [comment]
@cindrmon try launching brave with env. var GNUPGHOME set to your path

**Comment by cindrmon** [comment]
I recently added the `$GNUPGHOME` onto my `$PATH` file, and still nothing.
