### ISSUE TITLE
Keep audit data (which password was used where and when)

### ISSUE THREAD

**Issue by maximbaz** [browserpass/browserpass-extension#27]
I learned today that I had a malicious plugin installed for a specific known to me period of time, I wanted to find out which websites could have been compromised. Then I remembered about a wonderful `recent` object in localStorage of browserpass. 

My ideas was: 
- Download the entire object
- Keep only entries whose `when` is newer than the start time of the attack.
- For each remaining entry, rotate password

Unfortunately, this idea didn't work because we extensively hash the key 🙂 

https://github.com/browserpass/browserpass-extension/blob/98b6201f58fc7ed75ebdd7f0a60f8b831fb93a50/src/popup/popup.js#L159

I was wondering if hashing gives us any good benefits, and if no, can we not hash the key?

Alternatively, how about just adding a couple more fields in the object, for audit purposes? Now we have `count` and `when`, we could extend `when` to be a list, and add `host`, `store.id` and `login` in there.

**Comment by erayd** [comment]
It's hashed to keep the amount of data stored low (because that object gets loaded and iterated a lot) and to avoid leaking the username. The username is the only part that really *needs* to be hashed.

Regarding audit purposes - I don't want to turn `when` into a list, because performance, but what about just making a log?

**Comment by erayd** [comment]
Alternatively, we could switch from using a JSON object to using a proper database, which would mitigate the performance concern.
