### ISSUE TITLE
Firefox sometimes freezes when using Browserpass

### ISSUE THREAD

**Issue by RalfJung** [browserpass/browserpass-extension#309]
### General information

-   Operating system + version: Linux, Debian testing (KDE)
-   Browser + version: Firefox 107.0
-   Information about the host app:
    -   How did you install it? `apt install webext-browserpass`
        
    -   If installed an official release, put a version (`$ browserpass --version`): Package version 3.7.2-1+b6
-   Information about the browser extension:
    -   How did you install it?   `apt install webext-browserpass`
        
    -   Browserpass extension version as reported by your browser: 3.7.2

---

### Exact steps to reproduce the problem

1. Click the browserpass icon and select a password to fill

### What should happen?

It should unlock the GPG key and then put the password into the website.

### What happened instead?
*Sometimes*, Firefox just freezes entirely when I do this. The GPG key prompt appears, but after completing it Firefox is locked up.

This only started happening when I switched to Wayland, so that is probably related.

**Comment by maximbaz** [comment]
Hello! Apologies for the lack of response so far. 

To be honest it doesn't sound like a bug in this extension, but rather a bug in Firefox or in one of the gpg components. After all, whatever extensions do, I don't think they have the power to freeze a browser... 

Has it still been an issue for you?

I also use Browserpass in Firefox on Wayland, I've never experienced this issue. I don't think we'll be able to fix the problem without your help on getting some additional info, that could confirm that the issue is indeed in Browserpass, or where exactly it is.

For reference, Browserpass has nothing to do with unlocking GPG key, that is entirely handled within GPG - we simply call out to `gpg` to decrypt a file, and then it's up to gpg to decide if for example it needs to show pinentry dialog or not.

**Comment by maximbaz** [comment]
That would have been great if it was an upstream bug _somewhere_ that got fixed :slightly_smiling_face: Shall we close the issue for now? To anyone reading, feel free to comment if you also experience a similar issue, regardless if the ticket is closed or not.

**Comment by RalfJung** [comment]
Yeah I am fine with closing this for now.
