### ISSUE TITLE
Support multi-step authentication

### ISSUE THREAD

**Issue by DamienCassou** [browserpass/browserpass-extension#60]
I see some websites ask for credentials in 2 or 3 steps separated by a button click. In such a website, the user first enters her username or email, then clicks on a button, then enters her password, and then clicks a button.

On top of my head, these websites are like that:

- login.microsoftonline.com
- id.atlassian.com
- espace-client.enercoop.fr

Beyond those, more and more websites start including 2FA which is a step of its own.

Authenticating on these websites with browserpass-ce is annoying because I have to summon the extension several times to through all the steps. 2FA authentication is also annoying because I have to manually put the focus on the form field, type the numbers displayed by browserpass-ce, validate the form and then close browserpass-ce popup.

Would it be possible that browserpass-ce take care of these multi-step authentication websites?

**Comment by erayd** [comment]
@niftylettuce I have a mostly-working implementation of this now, tested working on Google. Do you have some examples of other sites I can test against?

**Comment by DamienCassou** [comment]
Erayd <notifications@github.com> writes:
> @niftylettuce I have a mostly-working implementation of this now,
> tested working on Google. Do you have some examples of other sites I
> can test against?

- https://id.atlassian.com/login
- https://login.microsoftonline.com
- https://espace-client.enercoop.fr/

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by DamienCassou** [comment]
- https://launchpad.37signals.com/signin

**Comment by DamienCassou** [comment]
- https://framavox.org (click the login button)

**Comment by erayd** [comment]
In light of #131, I am considering abandoning my work on this, for the following reasons:

 * This feature could be considered autosubmit-by-stealth, because it requires automatically submitting earlier stages of the login form to reach later ones.
 * I know we provide it as an option, but autosubmit is dangerous. This feature would potentially require auto-submitting multiple times in a row, which increases the risk further.
 * #131 mitigates most of the hassle of multi-step logins already, and follows the existing auto-submit setting.

I'd appreciate some feedback on this before making a final call - could anyone who cares about this please add your input.

// CC @maximbaz @DamienCassou @niftylettuce

**Comment by maximbaz** [comment]
I support your decision, it would have been a big and complex feature, with increased risk due to multiple auto-submit phases, with potentially even bigger risk and consequences in case something goes wrong and browserpass incorrectly auto-submits something it should have not.

**Comment by DamienCassou** [comment]
If you don't want to build on top of autosubmit, then your decision makes sense. Would you mind explaining, preferably in the README, why you think autosubmit is a problem?

In my opinion, activating autosubmit is a conscious decision. Additionally, using browserpass on a website requires selecting an entry from the popup which is another conscious decision. I think that, with two conscious decisions, the new feature is quite safe. You can make it even safer by whitelisting the websites where multi-step authentication is activated.

I think the current state is quite problematic. Either you believe that autosubmit is too dangerous and you either not impement it or you show a warning to the user in the preference UI. Or you believe the feature is safe enough and you build on top of it (you can even enable it by default).

My 2 cents.

**Comment by erayd** [comment]
> Would you mind explaining, preferably in the README, why you think autosubmit is a problem?

No problem. I have added this in #132.

> In my opinion, activating autosubmit is a conscious decision. Additionally, using browserpass on a website requires selecting an entry from the popup which is another conscious decision. I think that, with two conscious decisions, the new feature is quite safe.

They are conscious decisions about two different things. When users activate autosubmit, that's what they are thinking about. When they choose which entry to log in with, they generally are _not_ thinking about autosubmit, or the dangers it may pose.

> You can make it even safer by whitelisting the websites where multi-step authentication is activated.

It's possible to enable auto-submit on a per-site basis at the moment. **If** multi-step login is implemented, then it would use a similar setting, and could also be enabled per-site if desired.

> I think the current state is quite problematic. Either you believe that autosubmit is too dangerous and you either not impement it or you show a warning to the user in the preference UI. Or you believe the feature is safe enough and you build on top of it (you can even enable it by default).

Good point. I have added a _"not recommended"_ warning to the options screen in #132. Sadly, not implementing it isn't an option, as there are enough users who care strongly enough about it that leaving it out altogether would encourage forks.

Are you able to explain why multi-step is still a desirable feature? I'm seeing the following workflows:

### With multi-step
1. Select credentials from browserpass popup
2. Login step 1 is auto-filled & auto-submitted even if auto-submit is disabled
3. Login step 2 is auto-filled & auto-submitted if auto-submit is enabled

### Without multi-step, auto-submit enabled
1. Select credentials from browserpass popup
2. Login step 1 is auto-filled & auto-submitted
3. Press <kbd>Ctrl+Shift+F</kbd>
4. Login step 2 is auto-filled & auto-submitted.

Basically, this entire feature would exist in order to save a single keypress - I'm not convinced that this added convenience outweighs the risk.

The major risks I see, over ordinary autosubmit, are:
 - If multi-step is enabled, but auto-submit is not, the user may not realise that the first login step will be auto-submitted regardless.
 - If the initial form transits via an intermediate page that also contains a form, there's a chance that browserpass may attempt to fill the second step into that form (which will usually be the password). As such intermediate steps are often handled by a third party, and redirect back to the original page, that may mean that your password is leaked silently to a third party without the you being aware.
 - If the initial form leads to a page that isn't the stage-2 page (e.g. an error page, user-not-found page, disabled page, help docs, search page etc), browserpass may attempt to fill and submit your password on that page. Again, this would occur faster than you'd be able to catch it, and fast enough you may not notice.

**Comment by DamienCassou** [comment]
> No problem. I have added this in #132.

thank you.

> If multi-step login is implemented, then it would use a similar setting, and could also be enabled per-site if desired.

I like this solution. Good idea.

> Basically, this entire feature would exist in order to save a single keypress - I'm not convinced that this added convenience outweighs the risk.

You are limiting multi-step authentication to 2 steps. On https://outlook.office365.com/, there may be 5 steps:

1. choose an account from a list of accounts you recently used and click a button
2. if you don't pick from the list, you now have to enter a user name and click a button
3. you fill a password and click a button
4. you enter an otp token and click a button
5. you click a button to say you want to stay signed in

When I created the issue I had the dream that browserpass would let me bypass these 5 steps.

**Comment by maximbaz** [comment]
To be fair, I don't think we were ever headed to support (1) and (5), (and (4) in this extension), clicking some buttons on a page that doesn't contain a login form sounds error-prone and a bit out of scope for the project. If this feature was implemented, I would expect it would only allow you to skip step (3), everything else you'd do or trigger manually anyway - and now that we have <kbd>Ctrl+Shift+F</kbd>, skipping step (3) is worth much less, as you save only a single keystroke.

**Comment by maximbaz** [comment]
It seems we have established that implementing multi-login auth is not worth when <kbd>Ctrl+Shift+F</kbd> is available, therefore closing. Thanks for the suggestion and this discussion thought!

**Comment by C4K3** [comment]
One additional thing to consider is yubikeys with touch enabled, where it's

1. Ctrl-Shift-F
1. Touch Yubikey
1. Press submit
1. Ctrl-Shift-F
1. Touch Yubikey
1. Press submit

I personally don't use autoSubmit, and even then support for multi-step could reduce this to

1. Ctrl-Shift-F
1. Touch Yubikey
1. Press submit
1. Press submit

**Comment by maximbaz** [comment]
I also use yubikey but to be honest I cannot agree with this particular point to desire to cache the decrypted credentials, the whole reason for me to enable touch confirmation is that I want to know when my decrypted credentials are being used, if an app would decrypt them and then store unencrypted for some period of time and then even use several times, that feels like it defeats the whole point of touch confirmation...

**Comment by C4K3** [comment]
For me the point is that malware cannot dump all of my passwords at once, but only one at a time as I use them. Personally I would imagine a cache timeout to be something like 5-10 seconds. (And it could be made to clear it after it's filled the password into a form.)
