### ISSUE TITLE
icon inconsistency

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#63]
![image](https://user-images.githubusercontent.com/14617699/55425918-3c7b3280-558c-11e9-89f4-342ff6985416.png)

And the old icon were nicer (understandable) for my taste.

**Comment by maximbaz** [comment]
I can't repro 😞 I think your Firefox fetches the icon from the webstore, which still contains the old icon... For example I don't have this warning message you have... Maybe it's because I'm loading extension with "Load temporary add-on", but I see the new icon:

![image](https://user-images.githubusercontent.com/1177900/55427002-616ca700-5586-11e9-9f18-411ce95d6507.png)

How did you load the extension in the Firefox?

-------------

We will play with making the icon a bit more expressive (my current prototype is below), but it's not gonna return to the lock icon, sorry 😝 

![image](https://user-images.githubusercontent.com/1177900/55427163-b3adc800-5586-11e9-9090-05fe7d38a60c.png)

**Comment by 532910** [comment]
Even with "Load temporary add-on", after removing, I see old icon:

![image](https://user-images.githubusercontent.com/14617699/55427762-620a3b00-5590-11e9-948e-bddeb419c7e5.png)
![image](https://user-images.githubusercontent.com/14617699/55427798-72bab100-5590-11e9-8dde-1a983cf56cc3.png)

**Comment by maximbaz** [comment]
Well the lock icon is physically not present in the repo or the zip archive, so I must blame caching in your Firefox 😉

**Comment by 532910** [comment]
For new, clean ff profile I see new icon.
But for my profile I was need to remove addons.json, only after this I've seen new icon.

**Comment by maximbaz** [comment]
I think it won't be an issue when the extension will be updated via web store, but thanks for double-checking 👍 

Will close for now since it's nothing we can change in our code.

**Comment by 532910** [comment]
Fine. But it should be checked if it will be updated for normal users, after release.
