### ISSUE TITLE
Allow a single shortcut to replace Ctrl+Shift+L followed by Enter

### ISSUE THREAD

**Issue by adtac** [browserpass/browserpass-extension#75]
### General information

* Operating system + version: Linux / Arch Linux (64-bit)
* Browser + version: Chromium 67.0.3396.87 (Official Build)
* Information about the host app:
  * How did you install it?
    * Installed via a package manager, downloaded a pre-built binary, compiled yourself? **AUR**
  * If installed an official release, put a version: **2.0.21**
    * In the recent versions it can be obtained with `$ browserpass -v`.
    * If in doubt what version you have, download and re-install the latest version!
  * If built from sources, put a commit id (`$ git describe --always`): 
* Information about the browser extension:
  * How did you install it?
    * Installed via webstore, downloaded a pre-built extension, compiled yourself? **AUR**
  * Browserpass extension version as reported by your browser: **2.0.21**

---

### What should happen?

Currently I use the following combination to automatically input the password if I'm focused on the password field: (Ctrl+Shift+L) + (Enter). This will open the popup and select the best matching password (which is almost always the correct password, thanks to my directory structure).

I would like to combine this into one shortcut that automatically chooses and enters the best fitting password, if any. If there no matching passwords, the extension should do nothing.

**Comment by maximbaz** [comment]
I have implemented a PR for this, had to return back to <kbd>Ctrl+Shift+F</kbd> because as I discovered in my testing, <kbd>Ctrl+Shift+U</kbd> is weird, if a text field is focused, <kbd>Ctrl+Shift+U</kbd> does not trigger the extension, instead it enters an underlined letter "U". I have no clue why, but since <kbd>Ctrl+Shift+F</kbd> works well, let's go with it. It is mnemonic and can be changed in settings in all browsers.

**Comment by erayd** [comment]
> I have no clue why...

Probably because <kbd>CTRL+U</kbd> is the standard shortcut to toggle underlining, and either Chrome or something else on your system, is treating this as a <kbd>CTRL+U</kbd>. Regardless of whether this could be considered correct behavior or not, if it's a problem on your system, then it'll be a problem for others, so let's avoid it.
