### ISSUE TITLE
Add light theme

### ISSUE THREAD

**Issue by adtac** [browserpass/browserpass-extension#98]
### General information

-   Operating system + version: Arch Linux
-   Browser + version: Firefox Nightly (2019-04-13)
-   Information about the host app:
    -   How did you install it? `browserpass` from [community]
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
-   Information about the browser extension:
    -   How did you install it? Firefox Add-ons store
    -   Browserpass extension version as reported by your browser: 3.0.9

---

Browserpass v2 used to have a light theme and it was great. But it looks like v3 only supports a dark theme. I know that dark themes are more popular with developers (I, too, used to use dark themes), but a small minority of us prefer light themes. FWIW, dark text on light backgrounds is supposed to be more legible and readable to human eyes if the room you're in is well lit (which is the case for me).

As a worst case scenario, allow adding custom override CSS like available in the Tab Center Redux extension. But I'd much rather prefer a maintained light theme because div IDs and classes may change across releases, making custom CSS difficult to maintain.

**Comment by maximbaz** [comment]
Initially I had my reservations about supporting both themes (just because of the increased maintenance cost), but I believe it's a valid request and if we implement it right so that increased cost is minimal, I won't oppose a PR.

I propose to move everything color-related out of `popup.less` into `popup-dark.less`, and create a new `popup-light.less` file. Hopefully most of the styles will remain in a shared file, and the theme-related files will be minimal. Then add a class `theme-dark` or `theme-light` on `<body>` tag based on the current settings (keep dark theme a default), and in `popup-*.less` wrap everything in `.theme-dark { ... }` or `.theme-light { ... }` accordingly.

I don't think I'll be working on a light theme myself, so a PR is very welcome 🙂 

---------

If you would like to see a light theme, please upvote the issue, once someone proposes a PR I'll provide you with a test build and ping you for feedback.

--------

P.S. Since you are on Arch, I'll use this opportunity to recommend you to replace the addon from Web store with `browserpass-firefox` from `[community]`. I've just realized that this repo doesn't even mention this package in README, will fix in a moment.

**Comment by adtac** [comment]
Thanks, I've switched to the AUR version now.

And I'll try to submit a PR later this week. I can't maintain it, but I'm willing to do the initial work required.

**Comment by erayd** [comment]
@adtac Thank you - will keep an eye out for your PR.

Once it's merged, we will maintain it as part of the main codebase.

**Comment by maximbaz** [comment]
Please provide your feedback in https://github.com/browserpass/browserpass-extension/pull/120, I'm happy to create test builds for you if necessary.
